# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Koushik Shetty's blog
email: kou4307@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tech and general
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://koushik-shetty.github.io" # the base hostname & protocol for your site
github_username:  koushik-shetty
twitter_username: @KoushikShettyN3
linkedin: koushik-shetty

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
